name: handyman_provider_flutter
description: A new Flutter project.

publish_to: 'none'

version: 7.13.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^5.0.5
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.3
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.17.0
  url_launcher: ^6.1.9
  flutter_vector_icons: ^2.0.0

  #Firebase
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.12
  firebase_remote_config: ^3.0.10
  firebase_auth: ^4.2.6
  firebase_storage: ^11.0.11
  cloud_firestore: ^4.3.2
  firebase_pagination: ^3.0.0

  auto_size_text: 3.0.0
  flutter_custom_tabs: ^1.0.4
  dotted_border: ^2.0.0+3

  #image:
  image_picker: ^0.8.6+1
  photo_view: ^0.14.0
  file_picker: ^5.2.5
  lottie: ^2.2.0

  # PAYMENTS
  flutter_stripe: ^7.0.0
  razorpay_flutter: ^1.3.4
  flutterwave_standard: ^1.0.6
  cinetpay: ^1.0.6
#  flutter_braintree: ^3.0.0

  #notifications:
  onesignal_flutter: ^3.4.2

  flutter_typeahead: ^4.3.3

  #chart
  syncfusion_flutter_charts: ^20.4.49

  #map:
  geocoding: ^2.0.5

  flutter_html: ^3.0.0-alpha.3

  flutter_image_stack: ^0.0.6

  android_intent_plus: ^3.1.6

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/icons/
    - assets/lottie/

